baseURL = "https://dev.lgbt.sh/blog"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "@ly-nld's blog"
copyright = "Mikka 2023 - 2023"
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = ""
enableGitalk = false

# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
# clarity = "abcdefghzd"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "@ly-nld's blog" # will set 'og:site_name'
description = "My little diary"  # will set 'og:description'

[params.gitalk]
  owner = "user"
  repo = "repo name"
  client_id = "your client id"
  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[params.utterances]
repo="your repo"
term="[ENTER TERM HERE]"
label="your label"
theme="github-light"

# Please visit https://giscus.app/ to generate settings.
[params.giscus]
    data_repo="user/repo"
    data_repo_id="*****************************"    
    data_category="General"
    data_category_id="********************"
    data_mapping="pathname"
    data_strict="0"
    data_reactions_enabled="1"
    data_emit_metadata="0"
    data_input_position="bottom"
    data_theme="preferred_color_scheme"
    data_lang="en"
    crossorigin="anonymous"


[[menu.main]]
url = "/posts"
name = "Entries"
weight = 1
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/about/friends"
name = "Friends"
weight = 4
[[menu.main]]
url = "/about/mikka"
name = "About me"
weight = 5
[[menu.main]]
url = "https://dev.lgbt.sh"
name = "Profile Card"
weight = 6
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 7
